spring.application.name: back-smart-beauty-manager

spring.datasource.url: jdbc:postgresql://localhost:5431/db_smart_beauty_manager
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.datasource.driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: true
